# Generated by Django 3.0.6 on 2020-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('imd', models.CharField(max_length=122)),
                ('release', models.CharField(max_length=122)),
                ('link', models.CharField(max_length=122)),
            ],
        ),
    ]
