# Generated by Django 3.0.6 on 2020-05-27 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0003_movies_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='imd',
            new_name='imdb',
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='length',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
