# Generated by Django 3.0.6 on 2020-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0004_auto_20200527_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb',
            field=models.FloatField(max_length=122),
        ),
    ]
