# Generated by Django 3.0.6 on 2020-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0006_auto_20200527_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release',
            field=models.IntegerField(),
        ),
    ]
