# Generated by Django 3.0.6 on 2020-05-27 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0007_auto_20200527_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
