# Generated by Django 3.0.6 on 2020-05-27 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmyhub_app', '0008_movies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
